[keyboard]
name = "esp32s3_split"
product_name = "esp32s3_split"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "RMK"
chip = "esp32s3"
usb_enable = true


[layout]
rows = 4
cols = 12
layers = 7
keymap = [
    [
        ["-", "Q", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"],
        ["-", "A", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"],
        ["User3", "Z", "X", "C", "V", "-", "-", "-", "-", "-", "-", "-"],
        ["SWITCH", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"],
    ],
    [
        ["-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"],
        ["-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"],
        ["-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"],
        ["-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"],
    ],
    [
        ["-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"],
        ["-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"],
        ["-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"],
        ["-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"],
    ],
    [
        ["-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"],
        ["-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"],
        ["-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"],
        ["-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"],
    ],
    [
        ["-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"],
        ["-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"],
        ["-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"],
        ["-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"],
    ],
    [
        ["-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"],
        ["-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"],
        ["-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"],
        ["-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"],
    ],
    [
        ["-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"],
        ["-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"],
        ["-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"],
        ["-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"],
    ],
]

[split]
connection = "ble"

[split.central]
rows = 4
cols = 6
row_offset = 0
col_offset = 0

[split.central.matrix]
row_pins = ["GPIO8", "GPIO9", "GPIO10", "GPIO11"]
col_pins = ["GPIO6", "GPIO5", "GPIO4", "GPIO3", "GPIO2", "GPIO7"]
# RMK uses col2row as the default matrix diode direction, if you want to use a row2col matrix, add `row2col = true`
row2col = true

[[split.peripheral]]
rows = 4
cols = 6
row_offset = 0
col_offset = 6

[split.peripheral.matrix]
row_pins = ["GPIO11", "GPIO10", "GPIO9", "GPIO8"]
col_pins = ["GPIO7", "GPIO2", "GPIO3", "GPIO4", "GPIO5", "GPIO6"]
row2col = true

[ble]
enabled = true

[rmk]
split_peripherals_num = 1
split_central_sleep_timeout_seconds = 60

[dependency]
defmt_log = true
